Refactored helm-chart-annotations.md
redhat-certification/chart-verifier pull request #131
Opened 2021-05-20 22:05 UTC by iamrajiv

2021-05-21 02:54 UTC, baijum requested changes
Please remove duplicate text and only keep relevant modifications.

2021-05-21 02:54 UTC, baijum commented on docs/helm-chart-annotations.md
> +
This is a repetition of the below text

2021-05-21 02:54 UTC, baijum commented on docs/helm-chart-annotations.md
> +| charts.openshift.io/archs      | Comma separated list of supported architectures (e.g., x86_64, s390x,...) |
This is a repetition of the above text

2021-05-21 12:40 UTC, baijum commented
@iamrajiv Sorry, I am a bit lost here. Can you please update the title and description with what is the intent of this pull request?

As of now, looks like some relevant content has been removed.

2021-05-27 11:35 UTC, Srivaralakshmi reviewed
Looks good, from my side.

2021-06-08 07:59 UTC, baijum approved these changes
LGTM

2021-06-08 08:02 UTC, merged