[WIP] Add timeout option in the verify cmd
redhat-certification/chart-verifier pull request #261
Opened 2022-05-09 10:21 UTC by tisutisu

This PR will cover story: https://issues.redhat.com/browse/HELM-324

2022-05-12 09:37 UTC, isutton requested changes

2022-05-12 10:11 UTC, tisutisu commented on pkg/tool/helm_test.go
> +			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
@isutton these tests are running without cluster and not installing the chart and measuring timeout. These are previous test which were broken due to new parameters context is introduced. I took a random value to fix the broken test.

I think we should add the timeout specific tests here https://github.com/openshift-helm-charts/development/tree/main/tests/functional/features . WDYT?

2022-05-13 09:37 UTC, isutton commented on pkg/tool/helm_test.go
> +			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
A reproducible and automated test should exist to prove the timeout is respected according to what we advertise it works, and integration tests should play with the environment and different components to guarantee the timeout works.

Being more specific, tests should exist both in the functional features and unit level. If the positive test for this test case can't be achieved due to the absence of a cluster, then the test configuration should reflect that to verify at least that a timeout is respected in the case of a cluster is unreachable in this repository.

2022-05-16 10:49 UTC, tisutisu commented on pkg/tool/helm_test.go
> +			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
Added the unit test in the latest commit 474b8cc , which will check if the timeout is respected.

I think for integration test we can create new story and add the test here https://github.com/openshift-helm-charts/development/tree/main/tests/functional/features

2022-05-16 15:59 UTC, isutton commented on pkg/tool/helm_test.go
> +			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
I assume that testing a release should also be verified to be guarded by the timeout. Any reason to not apply the same idiom in `TestReleaseTesting`?

Does it break immediately when a cluster is not available? If so, then at least a zero'ed timeout could be fed to it and the method should return *before* calling `client.Run` in `helm.Test`. Things can hand between https://github.com/helm/helm/blob/63f98ccd60a8a4e90e7a3378de0337bc9238ca9f/pkg/action/release_testing.go#L53 and https://github.com/helm/helm/blob/63f98ccd60a8a4e90e7a3378de0337bc9238ca9f/pkg/action/release_testing.go#L53.

2022-05-17 06:12 UTC, tisutisu commented on pkg/tool/helm_test.go
> +			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
Sorry my bad. Applied the same idiom in the `TestReleaseTesting` in the latest commit ce7f654.

2022-05-17 10:38 UTC, tisutisu commented on pkg/tool/helm_test.go
> +			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
@isutton added the handling of zero or negative timeout case during release testing in the latest commit bb62b59 .

2022-05-17 13:38 UTC, isutton approved these changes

2022-05-17 20:47 UTC, mmulholla commented
@tisutisu 
Please also update the README file to include the new option and some words about it.

Also would be good if the message said what the timeout was set to and advise user to consider increasing the default timeout by setting the new option, if more time is needed.

2022-05-18 10:51 UTC, tisutisu commented
> @tisutisu Please also update the README file to include the new option and some words about it. For example if you need to set it to higher than 30 it would be advisable to submit the report because the certification process will use the default. see: https://github.com/redhat-certification/chart-verifier/blob/main/docs/helm-chart-checks.md#procedure
> 
> Also would be good if the message said what the timeout was set to and advise user to consider increasing the default timeout by setting the new option, if more time is needed.

Updated the readme file with words about timeout option in the latest commit 1762b72.
@mmulholla Would like know more about the improvement you suggested for error messages.

2022-05-18 15:50 UTC, mmulholla approved these changes
LGTM, thx for the updates.

2022-05-19 05:05 UTC, merged