Updates based on review of API documentaton
redhat-certification/chart-verifier pull request #276
Opened 2022-08-23 21:30 UTC by mmulholla

Update based in comments in closed PR: https://github.com/redhat-certification/chart-verifier/pull/271

2022-09-29 19:38 UTC, mmulholla commented on docs/helm-chart-api.md
> +The API is written using the go language and was created to enable services to run the chart verifier and obtain a report.
Done.

> @mmulholla Thanks for the changes. I have given some more suggestions. PTAL.
> 
> Also, I see that a good portion of my language suggestions on the use of active voice for descriptions has been ignored. Any particular reason why these language suggestions are ignored or not considered? Please clarify.

I have updated based on those comments, sorry I missed them, hopefully all good now.

2022-09-29 20:06 UTC, mmulholla commented on docs/helm-chart-api.md
> +- The following example does not include error checking code for clarity purposes.
@Srivaralakshmi, one thing I have not done is put the api functions into tables. Could not get comfortable with how the table would look and what headings to use. I think it is OK as is for now.

2022-09-30 07:19 UTC, Srivaralakshmi commented on docs/helm-chart-api.md
> +- GetContent: Gets the report as a string in either json or yaml format. ReportFormat values are defined and available in the report package:
```suggestion
- GetContent: Gets the report as a string in either the JSON or YAML format. ReportFormat values are defined and available in the report package:
```

@mmulholla Please incorporate this feedback for all similar instances.

2022-09-30 07:21 UTC, Srivaralakshmi commented on docs/helm-chart-api.md
> +- For full use of the chart-verifier see:
@mmulholla yes, please incorporate the suggestion

2022-09-30 07:22 UTC, Srivaralakshmi commented on docs/helm-chart-api.md
>  # Example:
@mmulholla Why is this still pending?

2022-09-30 07:27 UTC, Srivaralakshmi commented on docs/helm-chart-api.md
> +2. Set a profile.vendortype of redhat, un-enable the chart testing check, and run verify:
```suggestion
2. Set the `profile.vendortype` value to redhat, un-enable the chart testing check, and run verify:
```

2022-09-30 07:36 UTC, Srivaralakshmi requested changes
@mmulholla Nice work! Just some minor suggestions. PTAL and incorporate them. Thanks!

2022-09-30 11:34 UTC, mmulholla commented on docs/helm-chart-api.md
> +2. Set a profile.vendortype of redhat, un-enable the chart testing check, and run verify:
done.

2022-09-30 11:34 UTC, mmulholla commented
@Srivaralakshmi hopefully now all good

2022-09-30 16:51 UTC, Srivaralakshmi approved these changes

2022-09-30 16:52 UTC, Srivaralakshmi commented
@mmulholla Thanks for your patience and the changes implemented. Approved!

2022-10-03 11:37 UTC, merged